"use client";

// First sign-in: the organizer must add FoodLink to an authenticator app
// before they can post anything.

import { ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { ApiError, getJson, postJson } from "@/lib/client-api";
import { ErrorNote, Field, primaryButton, TextInput } from "./ui";

export function Setup2faForm() {
  const router = useRouter();
  const [setup, setSetup] = useState<{ qr: string; secret: string } | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let cancelled = false;
    getJson<{ qr: string; secret: string }>("/api/auth/setup-2fa")
      .then((r) => !cancelled && setSetup(r))
      .catch((err) => !cancelled && setError(err instanceof ApiError ? err.message : "Could not start setup."));
    return () => {
      cancelled = true;
    };
  }, []);

  async function submit(e: FormEvent) {
    e.preventDefault();
    setBusy(true);
    setError("");
    try {
      const r = await postJson<{ next: string }>("/api/auth/setup-2fa", { code });
      router.push(r.next);
      router.refresh();
    } catch (err) {
      setCode("");
      setError(err instanceof ApiError ? err.message : "Could not check the code.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <form onSubmit={submit} className="space-y-4">
      <div className="flex items-center gap-2.5 text-ink">
        <ShieldCheck className="h-6 w-6 text-forest" aria-hidden />
        <h1 className="font-display text-xl font-semibold">Set up two-step sign-in</h1>
      </div>
      <p className="text-sm text-muted">
        Listings reach people who cannot afford a wasted trip, so every organizer account is protected by a second
        step.
      </p>
      <ol className="list-decimal space-y-1 pl-5 text-sm text-body">
        <li>Install an authenticator app (Google Authenticator, Microsoft Authenticator or Authy).</li>
        <li>Scan this code with the app.</li>
        <li>Type the 6-digit code the app shows.</li>
      </ol>
      {setup ? (
        <div className="flex flex-col items-center gap-2 rounded-2xl bg-cream p-4">
          {/* A data: image generated by our own server. Nothing is fetched from another site. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={setup.qr} alt="QR code to add FoodLink to your authenticator app" width={220} height={220} className="rounded-lg" />
          <p className="text-xs text-muted">Cannot scan? Type this key into the app:</p>
          <code className="break-all rounded-lg bg-paper px-2 py-1 text-center text-sm text-ink">{setup.secret}</code>
        </div>
      ) : (
        !error && <div className="mx-auto h-[220px] w-[220px] animate-pulse rounded-lg bg-line/60" aria-hidden />
      )}
      <Field label="6-digit code from the app" htmlFor="setup-code">
        <TextInput
          id="setup-code"
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
          inputMode="numeric"
          autoComplete="one-time-code"
          required
          pattern="\d{6}"
          className="text-center font-display text-2xl tracking-[0.4em]"
        />
      </Field>
      <ErrorNote>{error}</ErrorNote>
      <button type="submit" disabled={busy || code.length !== 6 || !setup} className={`${primaryButton} w-full`}>
        Turn on two-step sign-in
      </button>
    </form>
  );
}
