#!/usr/bin/env node
// One-time local setup: creates .env.local with a fresh encryption key and
// three demo accounts. Secrets are generated on your machine and are never
// committed (.env.local is in .gitignore).
//
//   npm run setup            create .env.local if it does not exist
//   npm run setup -- --reset also delete the local database so it is re-seeded

import { randomBytes, randomInt } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { generateSecret } from "otplib";

const ENV_FILE = ".env.local";
const reset = process.argv.includes("--reset");

const WORDS = [
  "maple", "river", "otter", "cedar", "amber", "falcon", "garden", "harbor", "island", "juniper",
  "kettle", "lantern", "meadow", "nectar", "orchard", "pebble", "quartz", "ribbon", "saddle", "thistle",
  "umber", "valley", "willow", "yonder", "zephyr", "anchor", "basket", "candle", "dapple", "ember",
  "fiddle", "ginger", "hollow", "indigo", "jasper", "kindle", "linen", "marble", "nimble", "oyster",
  "pillow", "quiver", "rustic", "silver", "timber", "upland", "velvet", "walnut", "yarrow", "zigzag",
  "acorn", "bramble", "clover", "driftwood", "elder", "fennel", "granite", "heather", "ivory", "jade",
  "kelp", "lichen", "mossy", "north",
];

function passphrase() {
  const words = Array.from({ length: 4 }, () => WORDS[randomInt(WORDS.length)]);
  return `${words.join("-")}-${randomInt(1000, 10000)}`;
}

if (reset) {
  for (const f of ["data/foodlink.db", "data/foodlink.db-wal", "data/foodlink.db-shm"]) {
    if (existsSync(f)) rmSync(f);
  }
  console.log("Local database removed. It will be re-created and re-seeded on next start.");
}

if (existsSync(ENV_FILE)) {
  const current = readFileSync(ENV_FILE, "utf8");
  if (current.includes("FOODLINK_DATA_KEY=")) {
    console.log(`${ENV_FILE} already exists. Leaving it alone.`);
    console.log("Demo sign-in details are in that file. Run `npm run demo:codes` for the current 6-digit codes.");
    process.exit(0);
  }
}

const env = `# FoodLink local settings. Generated by \`npm run setup\`. NEVER commit this file.

# 32-byte key that encrypts organizer emails, phone numbers and 2FA secrets at rest.
# If you lose or change it, existing accounts can no longer be decrypted.
FOODLINK_DATA_KEY=${randomBytes(32).toString("base64")}

# ---- AI ----
# Leave ANTHROPIC_API_KEY empty to use the built-in rule-based parser only.
# With a key, FoodLink asks the model first and falls back to rules on any error.
ANTHROPIC_API_KEY=
# FOODLINK_AI_MODEL=claude-haiku-4-5-20251001
# FOODLINK_AI_MODE=rules   # force rules-only even when a key is set

# ---- Demo accounts (seeded into an empty database on first start) ----
# Organizer who already has two-factor set up.
DEMO_ORGANIZER_EMAIL=organizer@foodlink.test
DEMO_ORGANIZER_PASSWORD=${passphrase()}
DEMO_ORGANIZER_TOTP_SECRET=${generateSecret()}

# Human reviewer.
DEMO_REVIEWER_EMAIL=reviewer@foodlink.test
DEMO_REVIEWER_PASSWORD=${passphrase()}
DEMO_REVIEWER_TOTP_SECRET=${generateSecret()}

# Approved organizer who has NOT set up two-factor yet (use to demo QR enrollment).
DEMO_NEW_ORGANIZER_EMAIL=new.organizer@foodlink.test
DEMO_NEW_ORGANIZER_PASSWORD=${passphrase()}

# ---- Deployment (optional) ----
# DATABASE_URL=libsql://your-db.turso.io
# DATABASE_AUTH_TOKEN=
# FOODLINK_TRUST_PROXY=1   # set when running behind an HTTPS reverse proxy
`;

writeFileSync(ENV_FILE, env, { mode: 0o600 });
console.log(`Created ${ENV_FILE} with a new encryption key and three demo accounts.`);
console.log("");
console.log("Next steps:");
console.log("  1. npm run dev            start the app at http://localhost:3000");
console.log(`  2. open ${ENV_FILE}       demo emails and passwords are listed there`);
console.log("  3. npm run demo:codes     prints the current 6-digit codes for the demo accounts");
